### ISSUE TITLE
Multiple file upload in Service Publishing causes OptimisticLocking Exception

### ISSUE THREAD

**Issue by guidospadotto-profesia** [CloudOpting/cloudopting-manager#355] opened 2016-06-06 07:34 UTC
"when I tried to upload multiple files in the Upload needed files screen, exceptions like the one below are thrown"
`org.activiti.engine.ActivitiOptimisticLockingException: HistoricVariableInstanceEntity[id=1446080, name=fileId, revision=1, type=null] was updated by another transaction concurrently
at org.activiti.engine.impl.db.DbSqlSession.flushUpdates(DbSqlSession.java:875) ~[activiti-engine-5.19.0.2.jar:5.19.0.2]
at org.activiti.engine.impl.db.DbSqlSession.flush(DbSqlSession.java:614) ~[activiti-engine-5.19.0.2.jar:5.19.0.2]
at org.activiti.engine.impl.interceptor.CommandContext.flushSessions(CommandContext.java:212) ~[activiti-engine-5.19.0.2.jar:5.19.0.2]
at org.activiti.engine.impl.interceptor.CommandContext.close(CommandContext.java:138) ~[activiti-engine-5.19.0.2.jar:5.19.0.2]
at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:66) ~[activiti-engine-5.19.0.2.jar:5.19.0.2]
at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47) ~[activiti-spring-5.19.0.2.jar:5.19.0.2]
at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) ~[spring-tx-4.2.4.RELEASE.jar:4.2.4.RELEASE]
at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45) ~[activiti-spring-5.19.0.2.jar:5.19.0.2]
at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:31) ~[activiti-engine-5.19.0.2.jar:5.19.0.2]
at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:40) ~[activiti-engine-5.19.0.2.jar:5.19.0.2]
at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:35) ~[activiti-engine-5.19.0.2.jar:5.19.0.2]
at org.activiti.engine.impl.RuntimeServiceImpl.messageEventReceived(RuntimeServiceImpl.java:366) ~[activiti-engine-5.19.0.2.jar:5.19.0.2]
at eu.cloudopting.bpmn.BpmnService.upload(BpmnService.java:325) ~[classes/:na]`

**Comment by ildave** [comment] 2016-07-12 12:34
I made some tests, and it seems that when more than one file is uploaded, the  PublishArtifactStorageTask is called once for each file, and maybe this can mess with the transactions.
Is it possibile to call the PublishArtifactStorageTask just once, passing all the files together? Maybe this could be a way to avoid the issue.

**Comment by xeviscc** [comment] 2016-07-15 06:10
According mail of Davide: ". Maybe this can be fixed by sending all the files together and modifying the task to manage more than one file at once, can someone more expert in the Activity process advise about this?"
@gioppoluca do you have any advice on this?

**Comment by xeviscc** [comment] 2016-07-15 09:13
@guidospadotto-profesia @ildave we should be able to manage this before the ending of the next week.

**Comment by ildave** [comment] 2016-07-25 13:27
@xeviscc, is it possible from the fronted to send all the files data together in one call? The called url is
`/application/{idApp}/{processId}/file`
and it is called once for each file when Save is clicked.

If you can send all the files at once I think I can modify the `ApplicationResource.upload() `method to receive a list of file, and then manage them in the Activity task without changing the process.

@gioppoluca, do you think this can work?

**Comment by xeviscc** [comment] 2016-09-08 09:33
I would not recomend it because:
* It is possible for html5 compatible browsers only.
* We are sending other information a part from the file.

```javascript
Upload.upload({
  method: 'POST',
  url: endpoint,
  fields: { 'name': file.name, 'type' : type },
  file: file
}
```

**Comment by ildave** [comment] 2016-09-08 15:40
Luca suggested a workaround to avoid modifying the Activity Process.

We could add in the interface a checkbox that says "upload zip", to allow the user to load a zip file containing more than one file. Server side we can check that checkbox and if it is checked we can unzip the zip, check the files inside to get their name and type and save them one by one.

@xeviscc, do you think this is doable?

**Comment by xeviscc** [comment] 2016-09-09 08:15
It is doable, but it would not be better to zip it in the bakcend?

**Comment by ildave** [comment] 2016-09-09 08:21
The problem is that we cannot upload more than one file at once without changing the Activity Process below, which we don't want to do.
If the user upload a single zip file with more images in it we can workaround this issue.

**Comment by xeviscc** [comment] 2016-09-14 13:53
We will ask for only one file and we will create a checkbox to know if it is a zipped file or not.

**Comment by xeviscc** [comment] 2016-09-19 14:28
@ildave Implemented what we talked in the UI. Check it and test it.

**Comment by ildave** [comment] 2016-09-21 13:14
To complete this issue a change on the db structure must be done.

The table "application_media" has an unique index called "application_media_application_i" on the column "application_id". So, now only one row for each application can be added.
The unique constraint must be removed.

@cpopsa, can I perform the change directly on the db or something must be done on the platform?

**Comment by cpopsa** [comment] 2016-09-21 13:45
You are not supposed to change the db directly. Changes can be made only using Flyway db migration tool. For this you should create an sql file containing the change that you want to make and put it in database-component\src\main\resources\db\migration. The file should be named V1.6_somedescription.sql (see other sql files for example). Changes will be applied in db the next time you start the app.

**Comment by ildave** [comment] 2016-09-21 13:46
Ok, thanks!

**Comment by ildave** [comment] 2016-09-21 14:41
I have added the sql file to alter the index and pushed the code to manage the upload of a zip file when the checkbox is  checked, and to unzip it and store the single files in the db and in JackRabbit.
Commits:  
* f5aae7b1f4e4556602bb52cc8e774804f93cc4f1
* f1539d0fd3d5902fb58f6f36e75ba24676e23c43

**Closed by ildave** 2016-09-21 14:41 UTC
Labels: bug, high priority, in progress
