### ISSUE TITLE
Associate and persist a mail template to a published service

### ISSUE THREAD

**Issue by guidospadotto-profesia** [CloudOpting/cloudopting-manager#108] opened 2015-12-28 14:07 UTC
When publishing a service, it has to be possible to associate a template (or more than one?) for notification e-mail(s) that will be sent. Needs further analysis with @gioppoluca .

**Comment by gioppoluca** [comment] 2016-01-12 08:37
This is a duplicate of #109 or better #109 is just the service for sending mails using a template this issue cover the requirements I wrote in #109 but the mail service is just the isolation of the piece that cover the mail sending

**Closed** 2016-02-01 09:41 UTC
Labels: enhancement, Medium priority
