### ISSUE TITLE
Edit existing service - add item to library is not working

### ISSUE THREAD

**Issue by ciprianpavel** [CloudOpting/cloudopting-manager#311] opened 2016-03-30 10:26 UTC
Error while editing an existing service. The second page of the wizard generates the following Javascript stacktrace:

angular.js:11598 TypeError: Cannot read property 'applicationId' of null
    at Scope.$scope.saveConfigurationWizardTwo (publish.controller.js:195)
    at $parseFunctionCall (angular.js:12336)
    at callback (angular.js:21422)
    at Scope.$eval (angular.js:14388)
    at Scope.$apply (angular.js:14487)
    at HTMLButtonElement.<anonymous> (angular.js:21427)
    at HTMLButtonElement.jQuery.event.dispatch (jquery.js:4430)
    at HTMLButtonElement.elemData.handle (jquery.js:4116)

**Comment by xeviscc** [comment] 2016-03-30 10:27
Duplicate of https://github.com/CloudOpting/cloudopting-manager/issues/310

**Closed** 2016-03-30 10:27 UTC
Labels: bug, duplicate

**Comment by xeviscc** [comment] 2016-03-30 10:44
Sorry, it is a duplicated of #73
