### ISSUE TITLE
Navigating between service list get stuck

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-manager#406] opened 2016-09-16 07:59 UTC
I login as admin
go to service list
navigate in the list
get stuck with the circling balls (not only the PC but also mine)
Have to refresh the page and restart navigation

**Comment by xeviscc** [comment] 2016-09-16 08:38
Cannot reproduce the issue.
Which browser do you use?
When you say "navigate in the list" is clicking the arrows in the bottom to change the page? I've clicked it and the circling balls disappeared correctly.

**Comment by gioppoluca** [comment] 2016-09-16 08:55
It does not happen all the time.
I also seen that we have lots of broken pipe errors we did not have.

**Comment by xeviscc** [comment] 2016-09-16 09:28
I cannot reproduce it. Sometimes it may take some time to retrieve data due to the connection lag, but the circling balls always disappear.
Will close the issue.

For the broken pipes, open the proper issues with more information.

**Closed by xeviscc** 2016-09-16 09:28 UTC
Labels: bug, cannot reproduce

**Comment by xeviscc** [comment] 2016-09-16 09:36
Tested in Chrome and Firefox
