### ISSUE TITLE
Translate to ROMANIAN

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#301] opened 2016-03-29 05:40 UTC
All files has to be translated to ROMANIAN.
Check files at: https://github.com/CloudOpting/cloudopting-manager/tree/master/rest-component/src/main/webapp/i18n/ro

**Comment by ciprianpavel** [comment] 2016-03-30 09:13
Duplicate of #241. There are some strings remaining that will be translated as part of this issue.

**Comment by xeviscc** [comment] 2016-03-30 09:17
This is why I closed the #241. This is a subtask and from now on all updates has to be posted here.

**Comment by xeviscc** [comment] 2016-04-01 08:41
New string to translate at publish.json.
Check "description.template".

**Closed** 2016-04-15 08:17 UTC
Labels: enhancement
